name: zpi_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/band1.jpg
    - assets/images/band_pf.jpg
    - assets/images/band_bs.jpg
    - assets/images/band_akcent.jpg


  uses-material-design: true
