name: zpi_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  pdfx: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/


  uses-material-design: true
