name: zpi_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  path: ^1.9.0
  path_provider: ^2.1.4
  pdfx: ^2.8.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  dropdown_search: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/


  uses-material-design: true
